### ISSUE TITLE
Wrong macOs version on itch.io

### ISSUE THREAD

**Issue by linde9821** [LeHaine/ggo2022#1]
Just wanted to let you know that there are some issues with the macOs version on itchi.io.

The macOS version of the download on itchi.io is called `glutton-for-punishment-win64-littlekt-0.9.0`. I think it is actually the Windows version. 

Attempting to run the jar results in the following stacktrace:

```
[LWJGL] [ThreadLocalUtil] Unsupported JNI version detected, this may result in a crash. Please inform LWJGL developers.
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.lwjgl.glfw.GLFW.glfwInit(GLFW.java:1046)
	at com.lehaine.littlekt.LwjglContext$start$1.invokeSuspend(LwjglContext.kt:79)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:281)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.lehaine.littlekt.LwjglContext.start$core(LwjglContext.kt:73)
	at com.lehaine.littlekt.LittleKtApp.start(LittleKtApp.kt:14)
	at com.lehaine.game.LwjglAppKt.main(LwjglApp.kt:18)
	at com.lehaine.game.LwjglAppKt.main(LwjglApp.kt)
Caused by: java.lang.IllegalStateException: GLFW may only be used on the main thread and that thread must be the first thread in the process. Please run the JVM with -XstartOnFirstThread. This check may be disabled with Configuration.GLFW_CHECK_THREAD0.
	at org.lwjgl.glfw.EventLoop.<clinit>(EventLoop.java:30)
	... 14 more
```

**Comment by LeHaine** [comment]
Oof. Looks like I had them all mixed up somehow. Not sure how I did that. They all should now be correct. Thanks for letting me know!
